kind: Service
apiVersion: v1
metadata:
  name: helidon-database-demo
  labels:
    app: helidon-database-demo
spec:
  type: NodePort
  selector:
    app: helidon-database-demo
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: helidon-database-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helidon-database-demo
        version: v1
    spec:
      containers:
      - name: helidon-database-demo
        image: iad.ocir.io/cloud_pursuit_appdev/murphy/helidon-database-demo:latest
        imagePullPolicy: Always
        env:
          - name: javax_persistence_jdbc_user
            valueFrom:
              secretKeyRef:
                name: demo-database-db-params
                key: SECRET_USERNAME
          - name: javax_persistence_jdbc_password
            valueFrom:
              secretKeyRef:
                name: demo-database-db-params
                key: SECRET_PASSWORD
          - name: javax_persistence_jdbc_url
            valueFrom:
              secretKeyRef:
                name: demo-database-db-params
                key: SECRET_DBURL
        ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: ocirsecret
