apiVersion: v1

kind: Secret

metadata:

  name: demo-database-db-params

type: Opaque

data:

  SECRET_USERNAME : Ym9i
  SECRET_PASSWORD: T1JBREJwd2QjXzEy
  SECRET_DBURL: amRiYzpvcmFjbGU6dGhpbjpALy8xMzIuMTQ1LjM2LjEzMzoxNTIxL3BkYjEuZGF0YWJhc2UuYWNtZXZjbi5vcmFjbGV2Y24uY29t
