apiVersion: v1

kind: Secret

metadata:

  name: demo-database-db-params

type: Opaque

data:

  javax_persistence_jdbc_user : Ym9i
  javax_persistence_jdbc_password: T1JBREJwd2QjXzEy
  javax_persistence_jdbc_url: amRiYzpvcmFjbGU6dGhpbjpALy8xMzIuMTQ1LjM2LjEzMzoxNTIxL3BkYjEuZGF0YWJhc2UuYWNtZXZjbi5vcmFjbGV2Y24uY29t
